name = "Cultivate"
author = "ChefMooon"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4969046072684b3ae27185553cb3ff3ab58f03ee2ba4a701d8271afb1a04753"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
