name = "Cultivate"
author = "ChefMooon"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af47e45dcc4b17564c614d5f3ba02deac212f389f3e32d04a859fae0ee0eb81b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
