name = "Cultivate"
author = "ChefMooon"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fa41e03c0ffbf27b2e364a1427b8faa3e2e88317178b47355a0be29d63b2f80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
